version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: logiclike-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logiclike
      MYSQL_USER: logiclike_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/src/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

volumes:
  mysql_data: